### ISSUE TITLE
About

### ISSUE THREAD

**Issue by alaa-yasin** [GSG-G7/mental-snapp#25]
- [ ] **Route**

* `/about`   :About
* Protected : `false`
----
- [ ] **Description** 
This route tells the user more about the app and how it works.
---- 
- [ ]  **Structure**
This route contains:
- back button (it goes back to dashboard)
- heading (About)
- illustration
- 4 paragraphs with 4 subheadings 
- the logo
---
- [ ] **UI**

![20191024_134420](https://user-images.githubusercontent.com/51912186/67479142-18855880-f666-11e9-8f37-979c136aa708.jpg)

---

Relates: #6

**Comment by Fatmasiam** [comment]
Tablet and Ipad view need fixing
