### ISSUE TITLE
getAllJournals

### ISSUE THREAD

**Issue by alaa-yasin** [GSG-G7/mental-snapp#37]
## Backend Routes 
- [ ] **Route**

* route: ` /getAllEntries `  
* method : `GET`
 * firebase function `getAllJournals` 
---- 
- [ ] **Description** 
This route is responsible for getting all the entries that user enters.
---- 
- [ ]  **Response body** 
 ```js 
  res.body =  {
     grateful: {
title: ,
body:
  },
     challenge: {
title: ,
body:
  },
     developing: {
title: ,
body:
  },
     }

   }
```
This function relates to #21

**Comment by Fatmasiam** [comment]
and here we need `getCurrentMonthJournal`
