### ISSUE TITLE
Vag rounded font

### ISSUE THREAD

**Issue by MentalSnapp** [GSG-G7/mental-snapp#4]
Hi @teenie-quaggard 

I don't think I have permissions to add a font - would you be able to add the attached?

/Users/hannahchamberlain/Downloads/Vag Rounded Zip

**Comment by MentalSnapp** [comment]
Maybe I have to do them individually - 

/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded_bt.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded_lt.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-bold_cn.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-bold_ex.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-bold.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-bold(1).zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-boldwdregular.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-light_ex.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-light_italic.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-lighthollow.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-lightlefti.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-lightregular.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagrounded-thin.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagroundedblackssi.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagroundedblackssk.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagroundedlightssi.zip
/Users/hannahchamberlain/Downloads/Vag Rounded Zip/vagroundedltregular.zip

**Comment by MentalSnapp** [comment]
This is the link to the file: https://www.dropbox.com/sh/jfajkbp4i2pa24i/AAAuolMqC8EtE1pq8rHhBmEza?dl=0

**Comment by teenie-quaggard** [comment]
Thanks @MentalSnapp - I'll add this to the style guide!
