### ISSUE TITLE
User Testing Script

### ISSUE THREAD

**Issue by teenie-quaggard** [GSG-G7/mental-snapp#5]
@mentalsnapp - Here is the script that we will use tomorrow for user testing! Please let me know if you have any questions

# Mental Snapp User Testing Script

## **Intro ~3min**

Hi _____, my name is Kristina and this is Hannah. Thank you again for taking the time to participate in this study. Before we begin, I’m going to give you a brief overview of the test and how it will work.

*-->Small intro to the project*

This session is pretty straightforward — I’ll be giving you a broad task to complete and then asking questions as we go along. I anticipate that we will take approximately 20 minutes.

It’s really important to know that we are only testing the app, not you. You can’t do or say anything wrong here. Please feel free to let me know at any time if there’s something you like, dislike, if you’re confused, etc. I promise you won’t hurt my feelings.

Also, I’d like you to “think aloud” as much as possible. By that, I mean that I’d like you to speak your thoughts as often as you can. For example, you may be looking at a page, suddenly see something you didn’t see before and want to click on it. In that case, saying something like “this caught my eye so I’m going to see what it is” would be very useful.

If at any point you have questions, please don’t hesitate to ask. Do you have any questions so far?
Ok, Let’s get started.

## **Basic info about the user** ~2min
- job
- comfort with tech
- attitude concerning good mental health
- attitude concerning journaling

## **Complete the task** ~10min
- Sign up and find the dashboard (straight to dashboard, no log in)
- Add an entry (complete the full three steps)
- Add an entry (skip all three questions and add a freewrite)
- Add an entry and exit after the second question
- Find the heat map & understand what it does
- Click on a past entry and read it
- Delete an entry
- Find where to change password

**Comment by MentalSnapp** [comment]
Thanks @teenie-quaggard ! I'm away from the office at the moment so just on my phone. I don't know if it's because of that, but I'm struggling to find the invites now that I"ve got the email addresses! They're on my work google calendar, which I don't have access to. Sorry for the confusion. It might be easiest if I give you the email addresses to send the invites to, can you arrange?

The email addresses and order of interviews are: 
yasmin
sbrown
mafald
rant

Did you want 4 - I've got 4 lined up. They are all students at Goldsmiths. If we need to leave the last one off let me know. I'll send out a group email to all of them as well as the calendar invite, if you can send that. 

Thanks so much. 
@MentalSnapp

**Comment by teenie-quaggard** [comment]
Hi @MentalSnapp, I've added the invites.
Yasmin 9-9:30
Sbrown 9:30-10
Mafalda 10-10:30

Sorry since you mentioned that you only had three, I now have another engagement at 10:30, so will be unable to conduct that last one. If you'd like to ask them, I have availability from 5:30 - 6pm where I can conduct it by myself! 

Please ask rantw if that works for them and let me know. I can send them an invite.

I will delete the full addresses above for privacy reasons. Thanks!

**Comment by MentalSnapp** [comment]
Hi Kristina I’m running a bit late - should be there for 9. Tell me the
address for the testing?

**Comment by teenie-quaggard** [comment]
This script was used for user testing today. I will now close it since we will no longer need it.

**Comment by MentalSnapp** [comment]
rantw001@gold.ac.uk is Raymond’s email

**Comment by teenie-quaggard** [comment]
Hi @MentalSnapp - just a reminder not to post any private information on Github!
